server:
  context-path: /pastoral-canteen
  port: 8087
spring:
  datasource:
    url: jdbc:mysql://60.171.247.197:8090/pastoral_canteen?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&allowMultiQueries=true
    username: root
    password: Gepoint
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# website
projectUrl:
  pastoral-canteen: localhost:8087

